import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { PrismaClient } from '@prisma/client'

const Home = ({ posts }) => {
  return (
    <>
      <Head>
        <title>Gadfly</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h3>Posts</h3>
      <p className="lead">Lead Text</p>
      {posts.map((p, pid) => {
        return (
          <div key={pid}>
            <p><Link href={`/posts/${p.id}`}><a>{p.body}</a></Link></p>
          </div>
        )
      })}
    </>
  )
}

export default Home;

// Fetch all posts (in /pages/index.js)

export const getServerSideProps = async () => {
  const res = await fetch(`http://localhost:3000/api/posts/all`)
  const posts = await res.json();

  return {
    props : { posts }
  }
}
